services:
  bot:
    build: .
    env_file:
      - .env
    depends_on: 
      - db

  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
       - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: habits
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
  