name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          pip install flake8
          flake8 bot/ --max-line-length=120 --ignore=E302,W503,E211,E251,E303,E265,E231,W292,W391,W293,E225,W291,E303

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            cd ~/habit_tracker/bot
            git pull
            docker compose up --build -d